openapi: 3.1.0
info:
  title: Malphas Backend
  description: Endpoint documentation for the Malphas Backend
  version: 1.0.0
servers:
  - url: http://localhost:1234
    description: Local development  server
paths:
  /:
    get:
      summary: Status
      description: Status
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string