openapi: 3.1.0
info:
  title: Malphas Backend
  description: Endpoint documentation for the Malphas Backend
  version: 1.0.0
servers:
  - url: http://localhost:1234
    description: Local development  server
paths:
  /:
    get:
      tags:
        - Status
      operationId: statusEndpoint
      summary: Status endpoint
      description: Status endpoint
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string

  /login:
    post:
      tags:
        - Authentication
      operationId: login
      summary: Login
      description: Attempt to log in with the given credentials
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string

  /projects:
    get:
      tags:
        - Project
      operationId: listAllProjects
      summary: Get All Projects
      description: Get a list of all the projects of the current user
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    title:
                      type: string
                  required:
                    - id
                    - title
