openapi: 3.1.0
info:
  title: Malphas Backend
  description: Endpoint documentation for the Malphas Backend
  version: 1.0.0
servers:
  - url: http://localhost:1234
    description: Local development  server
paths:
  /:
    get:
      tags:
        - Status
      operationId: statusEndpoint
      summary: Status endpoint
      description: Status endpoint
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string

  /login:
    post:
      tags:
        - Authentication
      operationId: login
      summary: Login
      description: Attempt to log in with the given credentials
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/credentialsDto"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tokenDto"

  /register:
    post:
      tags:
        - Authentication
      operationId: register
      summary: register
      description: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/credentialsDto"
      responses:
        200:
          description: OK

  /scene:
    get:
      tags:
        - Scenes
      operationId: listAllScenes
      summary: Get All Scenes
      description: Get a list of all the scenes of the current user
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/sceneDto"
    post:
      tags:
        - Scenes
      operationId: createScene
      summary: Create a new scene
      description: Create a new scene
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/sceneCreationDto"
      responses:
        200:
          description: OK

  /circuit:
    post:
      tags:
        - Circuit
      operationId: postCircuit
      summary: Create a new circuit
      description: Create a new circuit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/circuitCreationDto"
      responses:
        200:
          description: OK
        400:
          description: InvalidCredentials
        500:
          description: InternalError

  /wire:
    post:
      tags:
        - Wire
      operationId: postWire
      summary: Create a new wire
      description: Create a new wire
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/wireCreationDto"
      responses:
        200:
          description: OK

components:
  schemas:
    credentialsDto:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
    sceneDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        author:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
      required:
        - id
        - author
        - name
        - description
    sceneCreationDto:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
      required:
        - name
        - description
    tokenDto:
      type: object
      properties:
        token:
          type: string
      required:
        - token
    circuitCreationDto:
      type: object
      properties:
        parent_scene:
          type: string
          format: uuid
        gateType:
          type: string
        location_x:
          type: int
        location_y:
          type: int
        parent_circuit:
          type: string
          format: uuid
      required:
        - parent_scene
        - gateType
        - location_x
        - location_y
    wireCreationDto:
      type: object
      properties:
        source_circuit:
          type: string
          format: uuid
        target_circuit:
          type: string
          format: uuid
        init_signal:
          type: bool
        number_input:
          type: int
        number_output:
          type: int
      required:
        - source_circuit
        - target_circuit
        - init_signal
        - number_input
        - number_output
