// tslint:disable
/**
 * Malphas Backend
 * Endpoint documentation for the Malphas Backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface CircuitDto
 */
export interface CircuitDto {
    /**
     * @type {string}
     * @memberof CircuitDto
     */
    id: string;
    /**
     * @type {string}
     * @memberof CircuitDto
     */
    parent_scene: string;
    /**
     * @type {number}
     * @memberof CircuitDto
     */
    location_x: number;
    /**
     * @type {number}
     * @memberof CircuitDto
     */
    location_y: number;
    /**
     * @type {string}
     * @memberof CircuitDto
     */
    parent_circuit?: string;
    /**
     * @type {string}
     * @memberof CircuitDto
     */
    gate_type: string;
}
