// tslint:disable
/**
 * Malphas Backend
 * Endpoint documentation for the Malphas Backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ErrorDto
 */
export interface ErrorDto {
    /**
     * @type {string}
     * @memberof ErrorDto
     */
    summary: string;
    /**
     * @type {string}
     * @memberof ErrorDto
     */
    description: string;
}
