// tslint:disable
/**
 * Malphas Backend
 * Endpoint documentation for the Malphas Backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ListAllProjects200ResponseInner
 */
export interface ListAllProjects200ResponseInner {
    /**
     * @type {string}
     * @memberof ListAllProjects200ResponseInner
     */
    id: string;
    /**
     * @type {string}
     * @memberof ListAllProjects200ResponseInner
     */
    title: string;
}
