// tslint:disable
/**
 * Malphas Backend
 * Endpoint documentation for the Malphas Backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface SceneUpdateDto
 */
export interface SceneUpdateDto {
    /**
     * @type {string}
     * @memberof SceneUpdateDto
     */
    id: string;
    /**
     * @type {string}
     * @memberof SceneUpdateDto
     */
    name: string;
    /**
     * @type {string}
     * @memberof SceneUpdateDto
     */
    description: string;
}
