// tslint:disable
/**
 * Malphas Backend
 * Endpoint documentation for the Malphas Backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface SignInRequest
 */
export interface SignInRequest {
    /**
     * @type {string}
     * @memberof SignInRequest
     */
    username: string;
    /**
     * @type {string}
     * @memberof SignInRequest
     */
    password: string;
}
