// tslint:disable
/**
 * Malphas Backend
 * Endpoint documentation for the Malphas Backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    Bool,
} from './';

/**
 * @export
 * @interface WireCreationDto
 */
export interface WireCreationDto {
    /**
     * @type {string}
     * @memberof WireCreationDto
     */
    source_circuit: string;
    /**
     * @type {string}
     * @memberof WireCreationDto
     */
    target_circuit: string;
    /**
     * @type {Bool}
     * @memberof WireCreationDto
     */
    init_signal: Bool;
    /**
     * @type {number}
     * @memberof WireCreationDto
     */
    number_input: number;
    /**
     * @type {number}
     * @memberof WireCreationDto
     */
    number_output: number;
}
