// tslint:disable
/**
 * Malphas Backend
 * Endpoint documentation for the Malphas Backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    Any,
} from './';

/**
 * @export
 * @interface WireDto
 */
export interface WireDto {
    /**
     * @type {string}
     * @memberof WireDto
     */
    id: string;
    /**
     * @type {string}
     * @memberof WireDto
     */
    source_circuit: string;
    /**
     * @type {string}
     * @memberof WireDto
     */
    target_circuit: string;
    /**
     * @type {boolean}
     * @memberof WireDto
     */
    init_signal: boolean;
    /**
     * @type {number}
     * @memberof WireDto
     */
    number_input: number;
    /**
     * @type {number}
     * @memberof WireDto
     */
    number_output: number;
    /**
     * @type {Any}
     * @memberof WireDto
     */
    location: Any;
}
