// tslint:disable
/**
 * Malphas Backend
 * Endpoint documentation for the Malphas Backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';
import type {
    LoginRequest,
} from '../models';

export interface LoginRequest {
    loginRequest: LoginRequest;
}

/**
 * no description
 */
export class AuthenticationApi extends BaseAPI {

    /**
     * Attempt to log in with the given credentials
     * Login
     */
    login({ loginRequest }: LoginRequest): Observable<string>
    login({ loginRequest }: LoginRequest, opts?: OperationOpts): Observable<AjaxResponse<string>>
    login({ loginRequest }: LoginRequest, opts?: OperationOpts): Observable<string | AjaxResponse<string>> {
        throwIfNullOrUndefined(loginRequest, 'loginRequest', 'login');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<string>({
            url: '/login',
            method: 'POST',
            headers,
            body: loginRequest,
        }, opts?.responseOpts);
    };

}
