// tslint:disable
/**
 * Malphas Backend
 * Endpoint documentation for the Malphas Backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts } from '../runtime';
import type {
    ListAllProjects200ResponseInner,
} from '../models';

/**
 * no description
 */
export class ProjectApi extends BaseAPI {

    /**
     * Get a list of all the projects of the current user
     * Get All Projects
     */
    listAllProjects(): Observable<Array<ListAllProjects200ResponseInner>>
    listAllProjects(opts?: OperationOpts): Observable<AjaxResponse<Array<ListAllProjects200ResponseInner>>>
    listAllProjects(opts?: OperationOpts): Observable<Array<ListAllProjects200ResponseInner> | AjaxResponse<Array<ListAllProjects200ResponseInner>>> {
        return this.request<Array<ListAllProjects200ResponseInner>>({
            url: '/projects',
            method: 'GET',
        }, opts?.responseOpts);
    };

}
