// tslint:disable
/**
 * Malphas Backend
 * Endpoint documentation for the Malphas Backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts } from '../runtime';

/**
 * no description
 */
export class StatusApi extends BaseAPI {

    /**
     * Status endpoint
     * Status endpoint
     */
    statusEndpoint(): Observable<string>
    statusEndpoint(opts?: OperationOpts): Observable<AjaxResponse<string>>
    statusEndpoint(opts?: OperationOpts): Observable<string | AjaxResponse<string>> {
        return this.request<string>({
            url: '/',
            method: 'GET',
        }, opts?.responseOpts);
    };

}
