// tslint:disable
/**
 * Malphas Backend
 * Endpoint documentation for the Malphas Backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';
import type {
    WireCreationDto,
    WireDto,
} from '../models';

export interface PostWireRequest {
    wireCreationDto: WireCreationDto;
}

/**
 * no description
 */
export class WireApi extends BaseAPI {

    /**
     * Get all wires
     * Get all wires
     */
    listAllWires(): Observable<Array<WireDto>>
    listAllWires(opts?: OperationOpts): Observable<AjaxResponse<Array<WireDto>>>
    listAllWires(opts?: OperationOpts): Observable<Array<WireDto> | AjaxResponse<Array<WireDto>>> {
        return this.request<Array<WireDto>>({
            url: '/wire',
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     * Create a new wire
     * Create a new wire
     */
    postWire({ wireCreationDto }: PostWireRequest): Observable<void>
    postWire({ wireCreationDto }: PostWireRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>
    postWire({ wireCreationDto }: PostWireRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(wireCreationDto, 'wireCreationDto', 'postWire');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>({
            url: '/wire',
            method: 'POST',
            headers,
            body: wireCreationDto,
        }, opts?.responseOpts);
    };

}
